image: python:3.11

variables:
  BUILD_TYPE: draft                             # Change it e.g. to "release" when the time comes
  APP_DIR: "Code/energy_prediction_system"      # Project path in the repository
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"   # Tell pip to use a cache directory inside the project workspace
  PIP_ROOT_USER_ACTION: ignore                  # Suppress the root user warning in Docker
  PIP_DISABLE_PIP_VERSION_CHECK: "1"            # Suppress the "new version available" notice

# Cache pip downloads to speed up subsequent jobs and pipeline runs
cache:
  paths:
    - .cache/pip

stages:
  - unit-tests
  - integration-tests
  - quality
  - security

# ========== UNIT TESTING stage ========== #

unit-tests:
  stage: unit-tests
  script:
    - echo "Assessing unit test coverage... "
    - cd $APP_DIR
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest --cov=src --cov-report=term-missing --cov-report=html:../../Testing/automated_tests/unit --cov-fail-under=70 --ignore=tests/integration
  artifacts:
    paths:
      - Testing/automated_tests/unit/
    expire_in: 1 week
  allow_failure: false

# ========== INTEGRATION TESTING stage ========== #

integration-tests:
  stage: integration-tests
  script:
    - echo "Assessing test coverage... "
    - cd $APP_DIR
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest --cov=src/data_pipeline --cov-report=term-missing --cov-report=html:../../Testing/automated_tests/integration --cov-fail-under=70 --ignore=tests/unit
  artifacts:
    paths:
      - Testing/automated_tests/integration/
    expire_in: 1 week
  allow_failure: false

# ========== QUALITY stage ========== #

coding_style:
  stage: quality
  script:
    - echo "Checking coding style with Ruff... "
    - cd $APP_DIR
    - pip install ruff==0.3.5
    - ruff check --verbose .
  allow_failure: true

code_complexity:
  stage: quality
  script:
    - echo "Checking code complexity with Ruff (McCabe)... "
    - cd $APP_DIR
    - pip install ruff==0.3.5
    - ruff check --select C90 --verbose .
  allow_failure: true


# ========== SECURITY stage ========== #

security:
  stage: security
  script:
    - echo "Running security tests with Ruff... "
    - cd $APP_DIR
    - pip install ruff==0.3.5
    - ruff check --select S --verbose .
  allow_failure: false # security should NEVER be compromised