image: python:3.11

variables:
  BUILD_TYPE: draft                             # Change it e.g. to "release" when the time comes
  APP_DIR: "Code/energy_prediction_system"      # Project path in the repository
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"   # Tell pip to use a cache directory inside the project workspace

# Cache pip downloads to speed up subsequent jobs and pipeline runs
cache:
  paths:
    - .cache/pip

stages:
  - unit-tests
  - integration-tests
  - quality
  - security

# ========== UNIT TESTING stage ========== #

unit-tests:
  stage: unit-tests
  script:
    - echo "Assessing unit test coverage... "
    - cd $APP_DIR
    - pip install pytest pytest-cov pandas entsoe-py cdsapi python-dotenv google-api-python-client google-auth-httplib2 google-auth-oauthlib
    - pytest --cov=src --cov-report=term-missing --cov-fail-under=70 --ignore=tests/integration
  allow_failure: true

# ========== INTEGRATION TESTING stage ========== #

integration-tests:
  stage: integration-tests
  script:
    - echo "Assessing test coverage... "
    - cd $APP_DIR
    - pip install pytest pytest-cov pandas entsoe-py cdsapi python-dotenv google-api-python-client google-auth-httplib2 google-auth-oauthlib
    - pytest --cov=src --cov-report=term-missing --cov-fail-under=70 --ignore=tests/unit
  allow_failure: true

# ========== QUALITY stage ========== #

coding_style:
  stage: quality
  script:
    - echo "Checking coding style... "
    - cd $APP_DIR
    - pip install flake8
    - flake8 --max-line-length=120 --extend-ignore=E203. # Ignoring white space before ':' in list slicing
  allow_failure: true

code_complexity:
  stage: quality
  script:
    - echo "Checking code complexity... "
    - cd $APP_DIR
    - pip install xenon
    - xenon -b C -m C -a C --ignore='venv' .
  allow_failure: true


# ========== SECURITY stage ========== #

security:
  stage: security
  script:
    - echo "Running security tests at application level... "
    - cd $APP_DIR
    - pip install bandit
    - bandit -r . -ll # (medium and high level of severity)
  allow_failure: false # security should NEVER be compromised