image: python:3.11


variables:
  BUILD_TYPE: draft                           # Change it e.g. to "release" when the time comes
  APP_DIR: "Code/energy_prediction_system"    # Project path in the repository

before_script:
  - python --version
  - echo "Hello, $GITLAB_USER_LOGIN!"
  - echo $REPO_NAME
  - echo $CI_COMMIT_BRANCH
  - echo $CI_PROJECT_DIR
  - pwd

stages:
    - unit-tests
    - integration-tests
    - quality
    - security


# ========== UNIT TESTING stage ========== #

unit-tests:
  stage: unit-tests
  before_script:
    - pip install pytest pytest-cov
  script:
  - echo "Assessing unit test coverage... "
  - cd $APP_DIR
  - pytest --cov=src --cov-report=term-missing --cov-fail-under=70 --ignore=tests/integration
  allow_failure: true


# ========== INTEGRATION TESTING stage ========== #

integration-tests:
  stage: integration-tests
  before_script:
    - !reference [before_script]
    - pip install pytest pytest-cov
  script:
  - echo "Assessing test coverage... "
  - cd $APP_DIR
  - pytest --cov=src --cov-report=term-missing --cov-fail-under=70 --ignore=tests/unit
  allow_failure: true


# ========== QUALITY stage ========== #

coding_style:
  stage: quality
  before_script:
    - !reference [before_script]
    - pip install flake8
  script:
    - echo "Checking coding style... "
    - cd $APP_DIR
    - flake8 --max-line-length=120 .
  allow_failure: true # default is false;

code_complexity:
  stage: quality
  before_script:
    - !reference [before_script]
    - pip install xenon
  script:
    - echo "Checking code complexity... "               # -b A : At least one block has a complexity rank higher than A (i.e. B, C, D, E or F)
    - cd $APP_DIR                                       # -m A : At least one module has a complexity rank higher than A (i.e. B, C, D, E or F)
    - xenon -b C -m C -a C --ignore='venv' .            # -a A : Average complexity has rank higher than A (i.e. B , C, D, E or F)
  allow_failure: true # default is false;


# ========== SECURITY stage ========== #

security:
  stage: security
  before_script:
    - !reference [before_script]
    - pip install bandit
  script:
    - echo "Running security tests at application level... "
    - cd $APP_DIR
    - bandit -r . -ll # (medium and high level of severity)
  allow_failure: false # set to false - security should NEVER be compromised



